FATAL:   Image file already exists: "/gpfs/home/jl24018/openmm-md.sif" - will not overwrite
2024-11-18 10:04:00,943 - src.plumed.main - INFO - Output directory: ../../data/241109_INFconstruct/output/Z1-B50W/241118
2024-11-18 10:04:00,943 - src.plumed.main - INFO - ==================== Running Z1-B50W ====================
2024-11-18 10:04:00,943 - src.plumed.main - INFO - Running with timestep 2 fs and mdtime 2 ns
2024-11-18 10:04:00,943 - src.plumed.main - INFO - Energy barrier 200 kJ/mol for OPES
2024-11-18 10:04:00,943 - src.plumed.main - INFO - Pace 500 steps of depositing bias in OPES.
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:290: UserWarning: PDB file is missing resid information.  Defaulted to '1'
  warnings.warn("PDB file is missing resid information.  "
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:304: UserWarning: Serial numbers went over 100,000.  Higher serials have been guessed
  warnings.warn("Serial numbers went over 100,000.  "
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:423: UserWarning: Invalid atom serials were present, bonds will not be parsed
  warnings.warn("Invalid atom serials were present, bonds will not"
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:215: UserWarning: Invalid atom serials were present, bonds will not be parsed
  warnings.warn("Invalid atom serials were present, "
2024-11-18 10:05:42,182 - src.plumed.opes - INFO - Using CUDA device 0
Traceback (most recent call last):
  File "/gpfs/home/jl24018/projects/openmm-md/scripts/241118_INFconstruct/run.py", line 70, in <module>
    main(
  File "/gpfs/home/jl24018/projects/openmm-md/src/plumed/main.py", line 102, in main
    opes(
  File "/gpfs/home/jl24018/projects/openmm-md/src/plumed/opes.py", line 173, in opes
    simulation.step(equilibrationSteps)
  File "/opt/conda/lib/python3.12/site-packages/openmm/app/simulation.py", line 150, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/opt/conda/lib/python3.12/site-packages/openmm/app/simulation.py", line 229, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/openmm/openmm.py", line 3268, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
